server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false # 关闭缓存
  rabbitmq:
    host: 192.168.1.62
    virtual-host: /leyou
    username: leyou
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5 # 每5秒拉取一次服务
