server:
  port: 8085
spring:
  application:
    name: user-service
  # mysql配置
  datasource:
    url: jdbc:mysql://192.168.1.62:3306/leyou
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  # redis配置
  redis:
    host: 192.168.1.62
  # rabbitmq配置
  rabbitmq:
    host: 192.168.1.62
    virtual-host: /leyou
    username: leyou
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo